### PR TITLE
ISI Tray

### LINKED ISSUE #9: Product Safety Information
Safety_Info

### LINKED ISSUE #74: Gammagard-liquid hero tag-line should be orange
This is for the first line below the logo. Hex should be #f89a38 = var --gammagard-liq:
Screenshot 2023-07-27 at 9 36 13 AM

### LINKED ISSUE #76: Gammaguard SD and Liquid Hero Button, should have an orange font color
see screenshot
Screenshot 2023-07-27 at 10 27 22 AM

### LINKED ISSUE #81: Feat-isi Tray - Expand button chopped on the right side onload
Screenshot 2023-07-27 at 3 34 43 PM

### LINKED ISSUE #82: Feat-isi Tray - Collapse button Should show as soon as scroll is started
here is a link to the isi tray buttons on scroll. New site should be the same.....

https://feat-isi--takeda-ihs--hlxsites.hlx.page/

### PR DESCRIPTION
**Pull request by bstopp**
Fix #9 
Fix #82 
Fix #81 
Fix #76 
Fix #74

Test URLs:
- After: https://feat-isi--takeda-ihs--hlxsites.hlx.page/drafts/stopp/product-detail

### CODE REVIEW

**Comment by DanCollinz** [comment]
Expand button chopped on the right side, its just under the browser windows right side
Screenshot 2023-07-27 at 3 34 05 PM

**Comment by DanCollinz** [comment]
Collapse button Should show as soon as scroll is started see screen replay: [replay](https://mytakeda.sharepoint.com/sites/Takeda-Adobe-Franklin/Shared%20Documents/Forms/AllItems.aspx?FolderCTID=0x0120003D55E1FC1870AA4286A6134724D74715&id=%2Fsites%2FTakeda%2DAdobe%2DFranklin%2FShared%20Documents%2FGeneral%2Fihs%2Dadobe%2Dfranklin%2Dcontent%2Fdrafts%2Fstopp%2FScreen%20Recording%202023%2D07%2D27%20at%203%2E38%2E15%20PM%2Emov&viewid=4efca9f8%2D9bed%2D4b38%2Dbd8b%2D76790a121310&parent=%2Fsites%2FTakeda%2DAdobe%2DFranklin%2FShared%20Documents%2FGeneral%2Fihs%2Dadobe%2Dfranklin%2Dcontent%2Fdrafts%2Fstopp)

**Comment by bstopp** [comment]
> Expand button chopped on the right side, its just under the browser windows right side 

Does this happen on the live site, today?

**Review by lwintch — APPROVED** [review]
Looks great!  Tested great.

**Pull request merged**
